package mega;

import java.awt.Graphics2D;
import robocode.*;
import robocode.util.*;

/**
 * The base abstract class for all Robocode components (Movement, Gun, Radar).
 * This class provides a common interface and basic lifecycle methods that
 * all components can implement.
 * Components are designed to work with a shared {@link State} object, allowing
 * them to access and update the robot's current battle information.
 * 
 * @author Gates
 */
public abstract class Component {
    /**
     * The shared {@link State} object containing information about the robot's
     * current battle status, including its own position, enemy data, and more.
     */
    protected State state;

    /**
     * Constructs a new Component with the given battle {@link State}.
     * @param state The shared {@link State} object for the robot.
     */
    public Component(State state) {
        this.state = state;
    }

    /**
     * Executes the main logic for this component. This method is called
     * repeatedly during each turn of the battle. Subclasses must implement
     * their specific behavior here.
     */
    public abstract void execute();

    /**
     * Called when this robot collides with another robot.
     * Subclasses can override this method to define specific behavior
     * upon robot collision.
     * @param e The HitRobotEvent generated by the collision.
     */
    public void onHitRobot(HitRobotEvent e) {
        // Default implementation does nothing.
    }
    
    /**
     * Called when this robot collides with a wall.
     * Subclasses can override this method to define specific behavior
     * upon hitting a wall.
     * @param e The HitWallEvent generated by the collision.
     */
    public void onHitWall(HitWallEvent e) {
        // Default implementation does nothing.
    }
    
    /**
     * Called when the robot is painted on the screen.
     * Subclasses can override this method to draw custom graphics on the
     * battlefield for debugging or visualization purposes.
     * @param g The Graphics2D object used for drawing.
     */
    public void onPaint(Graphics2D g) {
    	// Default implementation does nothing.
    }
}