package mega;

import robocode.*;
import robocode.util.Utils;

/**
 * Implements a "Spin" movement strategy.
 * This strategy causes the robot to continuously spin its body while moving,
 * which can make it a harder target to hit due to unpredictable changes
 * in heading and position. It's often used in melee battles to create chaos
 * or to quickly change direction.
 * 
 * The robot will attempt to maintain a constant spin and a moderate forward speed.
 * 
 * @author Gates
 */
public class MovementSpin extends Movement {

	/**
	 * Constructs a new MovementSpin component with the given battle {@link State}.
	 * @param state The shared {@link State} object for the robot.
	 */
	public MovementSpin(State state) {
		super(state);
	}

	/**
	 * Executes the Spin movement strategy for one turn.
	 * Sets a high rotation rate for the robot's body to make it spin
	 * continuously, and sets a constant speed for forward movement.
	 * The actual turning and moving commands are applied by the main robot
	 * based on these calculated values.
	 */
	@Override
    public void execute() {
		// Set a very high rotation rate for the robot's body.
		// The Robocode engine will cap this to its maximum possible turn rate.
		this.rotation = 10; // Radians per turn, equivalent to a full circle over many turns.
		// Set a constant speed for continuous movement.
		this.speed = 5; // Pixels per turn.
		
		// The direct call to this.state.owner.ahead(10000) was removed
		// as movement commands should be handled by the main robot (Boilerplate)
		// through setVelocityRate based on this.speed.
	}
	
	/**
	 * Called when this robot collides with another robot.
	 * If the collision was caused by this robot ({@code e.isMyFault()}),
	 * it attempts to adjust its rotation slightly to recover and continue spinning.
	 * @param e The HitRobotEvent generated by the collision.
	 */
	@Override
	public void onHitRobot(HitRobotEvent e) {
		if (e.isMyFault()) {
			// If we hit another robot, slightly adjust our spin to try and get unstuck
			// or to continue the spinning motion more effectively.
			this.rotation = 10; // Re-apply the spin rotation
		}
	}

}
